#!/bin/bash

cd ~/Documents/FractalBootcamp/projects

read -p "Enter Vite or Remix: " react_type

if [ "$react_type" == "Vite" ]; then
    read -p "Give the new app a name: " app_name
    
    if [ -z "$app_name" ]; then
        echo "App name cannot be empty."
        exit 1
    fi
    
    npm create vite@latest $app_name -- --template react-swc-ts
    
    cd $app_name
    
    read -p "Would like to setup an Express server  (Y or N): " express_server
    
    if [ "$express_server" == "Y" ]; then
        
        cp /Users/mehulbehera/bin/boilerplateserver.ts ./server.ts
        npm i express
        npm i cors
        
    fi
    
    
    
    
    elif [ "$react_type" == "Remix" ]; then
    
    echo "You Typed Remix"
    exit 1
    
else
    
    echo "Incorrect Input"
    exit 1
    
fi

read -p "Would you like to setup a database? (Y or N): " database_res

if [ "$database_res" == "Y" ]; then
    
    cp /Users/mehulbehera/bin/.env ./env
    cp /Users/mehulbehera/bin/.env.local ./.env.local
    cp /Users/mehulbehera/bin/docker-compose.yml ./docker-compose.yml
    npm install prisma --save-dev
    npx prisma init --datasource-provider postgresql
    npm install @prisma/client
    cp /Users/mehulbehera/bin/client.ts ./client.ts
    
fi

npm install
code .